# Generated by Django 6.0.1 on 2026-02-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
