# Generated by Django 6.0.1 on 2026-02-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_orders_order_id_orders_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AddField(
            model_name='orders',
            name='ord_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
