# Generated by Django 6.0.1 on 2026-02-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_update',
            new_name='orderupdate',
        ),
    ]
