# Generated by Django 6.0.1 on 2026-02-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_order_update_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_id',
            new_name='ord_id',
        ),
    ]
