# Generated by Django 6.0.1 on 2026-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_order_id_orderupdate_ord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='ord_id',
            new_name='order_id',
        ),
    ]
