# Generated by Django 6.0.1 on 2026-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_orders_paid_orders_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
